// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgwofufhtkbqcvcwsuen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnd29mdWZodGticWN2Y3dzdWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTkzMDAsImV4cCI6MjA2Nzk5NTMwMH0.qjaHMwF9ej7SMm53IKmzUimuC-altGiGSqVRppJ0Aks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});